name: lint

on:
  push:
    branches: [main]

jobs:
  go-lint:
    name: Run lints
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      uses: DavidAnson/markdownlint-cli2-action@v9
      with:
        globs: '**/*.md'
