name: postmortem report

on:
  push:
    - main

jobs:
  build:
    name: PostMortem report
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: markdownlint-cli2-action
      uses: DavidAnson/markdownlint-cli2-action
